site_name: Computational Tutorials
site_description: Practical guides for HPC users and operators
repo_url: https://github.com/wintermutant/computational-tutorials
repo_name: computational-tutorials

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight

nav:
  - Home: index.md
  - VSCode: vscode.md
  - Anvil Composable (CLI): anvil-composable-cli.md
  - Anvil Notebook Kernel: jupyter-kernel-anvil-notebook.md

# Copyright
copyright: Copyright &copy; 2026 Dane Deemer